services:
- type: web
  name: retool
  env: docker
  plan: standard
  healthCheckPath: /api/checkHealth
  autoDeploy: false
  envVars:
  - fromGroup: retool
  - key: JWT_SECRET
    generateValue: true
  - key: NODE_ENV
    value: production
  - key: ENCRYPTION_KEY
    generateValue: true
  - key: FORCE_SSL
    value: true
  - key: HEROKU_HOSTED
    value: true